In [ ]:
import pandas as pd
df_movies= pd.read_csv("IMDB-Movie-Data.csv")

df_movies.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
display(type(df_movies))

pandas.core.frame.DataFrame

In [ ]:
df_movies.tail(2)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [ ]:
df_movies.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [ ]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [ ]:
# number of all nulls in every column summed
df_movies.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [ ]:
df_movies.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [ ]:
# rename() :: method ---> for renaming column names
df_movies.rename(columns = {'Runtime (Minutes)' : 'Runtime_in_Minutes', 'Revenue (Millions)': 'Revenue_in_Millions'},
                 inplace = True)
# check the new column names
df_movies.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime_in_Minutes', 'Rating', 'Votes', 'Revenue_in_Millions',
       'Metascore'],
      dtype='object')

In [ ]:
# using list comprehensions with column names
# let's try lowering all columns' names in one line of code
df_movies.columns = [column.lower() for column in df_movies.columns]
# check column names
df_movies.columns

Index(['rank', 'title', 'genre', 'description', 'director', 'actors', 'year',
       'runtime_in_minutes', 'rating', 'votes', 'revenue_in_millions',
       'metascore'],
      dtype='object')

In [ ]:
# handling duplicate rows
# # to create a dataset with row duplicates just douple our movie dataset
df_temp = pd.concat([df_movies, df_movies], axis = 0)
# investigate the shape
df_temp.shape

(2000, 12)

In [ ]:
# view df_temp sorted
df_temp.sort_values(by='title', axis=0, inplace=True)
df_temp.head()

,rank,title,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore
507,508,(500) Days of Summer,"Comedy,Drama,Romance",An offbeat romantic comedy about a woman who d...,Marc Webb,"Zooey Deschanel, Joseph Gordon-Levitt, Geoffre...",2009,95,7.7,398972,32.39,76.0
507,508,(500) Days of Summer,"Comedy,Drama,Romance",An offbeat romantic comedy about a woman who d...,Marc Webb,"Zooey Deschanel, Joseph Gordon-Levitt, Geoffre...",2009,95,7.7,398972,32.39,76.0
118,119,10 Cloverfield Lane,"Drama,Horror,Mystery","After getting in a car accident, a woman is he...",Dan Trachtenberg,"John Goodman, Mary Elizabeth Winstead, John Ga...",2016,104,7.2,192968,71.90,76.0
118,119,10 Cloverfield Lane,"Drama,Horror,Mystery","After getting in a car accident, a woman is he...",Dan Trachtenberg,"John Goodman, Mary Elizabeth Winstead, John Ga...",2016,104,7.2,192968,71.90,76.0
696,697,10 Years,"Comedy,Drama,Romance","The night before their high school reunion, a ...",Jamie Linden,"Channing Tatum, Rosario Dawson, Chris Pratt, J...",2011,100,6.1,19636,0.20,NaN

In [ ]:
# Now we will try to drop the full-row duplicates
df_temp.drop_duplicates(inplace=True)
# check the shape
df_temp.shape

(1000, 12)

In [ ]:
df_temp = pd.concat([df_movies, df_movies], axis = 0)
# check shape
df_temp.shape

(2000, 12)

In [ ]:
df_temp.drop_duplicates(inplace=True, keep=False)
# check the shape
df_temp.shape

(0, 12)

In [ ]:
# slicing and selecting in dataframes
# set the index to the 'title' column
df_movies.set_index('title',inplace=True)
df_movies.head()

,rank,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore
title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [ ]:
# selecting specific rows/columns
#df.loc[]: used to select specific rows/columns by names using the following syntax :
#df.loc[rows_range_by_names: columns_range_by_names]
#df.iloc[]: used to select specific rows/columns by number index using the following syntax :
#df.iloc[rows_range_by_numbers: columns_range_by_numbers]

split_loc0 = df_movies.loc['Split', 'rank': 'actors' ]
# print the split
split_loc0

rank                                                           3
genre                                            Horror,Thriller
description    Three girls are kidnapped by a man with a diag...
director                                      M. Night Shyamalan
actors         James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Name: Split, dtype: object

In [ ]:
pd.DataFrame(split_loc0).T

,rank,genre,description,director,actors
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar..."

In [ ]:
split_loc1 = df_movies.loc['Split', :  ]
# print the split
pd.DataFrame(split_loc1).T

,rank,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0

In [ ]:
# Another form of loc
split_loc2= df_movies.loc['Split']
pd.DataFrame(split_loc2).T

,rank,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0

In [ ]:
split_iloc0 = df_movies.iloc[2]
# print the split
pd.DataFrame(split_iloc0).T

,rank,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0

In [ ]:
df_movies_subset = df_movies[['genre','rating']]
df_movies_subset.head()

                                            genre  rating
title
Guardians of the Galaxy   Action,Adventure,Sci-Fi     8.1
Prometheus               Adventure,Mystery,Sci-Fi     7.0
Split                             Horror,Thriller     7.3
Sing                      Animation,Comedy,Family     7.2
Suicide Squad            Action,Adventure,Fantasy     6.2

In [ ]:
df_movies_subset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   genre   1000 non-null   object
 1   rating  1000 non-null   float64
dtypes: float64(1), object(1)
memory usage: 55.7+ KB

In [ ]:
# include all object columns
df_movies_str = df_movies.select_dtypes(include='object')
df_movies_str.head()

,genre,description,director,actors
title,,,,
Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S..."
Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa..."
Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar..."
Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma..."
Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D..."

In [ ]:
# missing values handling
df_movies_cp= df_movies.copy()

In [ ]:
# remove all rows with null values
df_movies.dropna( axis=0, inplace= True)
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 838 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   rank                 838 non-null    int64
 1   genre                838 non-null    object
 2   description          838 non-null    object
 3   director             838 non-null    object
 4   actors               838 non-null    object
 5   year                 838 non-null    int64
 6   runtime_in_minutes   838 non-null    int64
 7   rating               838 non-null    float64
 8   votes                838 non-null    int64
 9   revenue_in_millions  838 non-null    float64
 10  metascore            838 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 78.6+ KB

In [ ]:
df_movies_cp.isnull().sum()

rank                     0
genre                    0
description              0
director                 0
actors                   0
year                     0
runtime_in_minutes       0
rating                   0
votes                    0
revenue_in_millions    128
metascore               64
dtype: int64

In [ ]:
mean_revenue = df_movies_cp.revenue_in_millions.mean()
mean_revenue

82.95637614678898

In [ ]:
df_movies_cp.revenue_in_millions.fillna(mean_revenue, inplace=True)
df_movies_cp.isnull().sum()

<ipython-input-30-5c4fc4ec5acb>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_movies_cp.revenue_in_millions.fillna(mean_revenue, inplace=True)

rank                    0
genre                   0
description             0
director                0
actors                  0
year                    0
runtime_in_minutes      0
rating                  0
votes                   0
revenue_in_millions     0
metascore              64
dtype: int64

In [ ]:
# filtering
df_movies_ridley_scott = df_movies[df_movies ['director'] == 'Ridley Scott']
df_movies_ridley_scott.head()

,rank,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore
title,,,,,,,,,,,
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
The Martian,103,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
Robin Hood,388,"Action,Adventure,Drama","In 12th century England, Robin and his band of...",Ridley Scott,"Russell Crowe, Cate Blanchett, Matthew Macfady...",2010,140,6.7,221117,105.22,53.0
American Gangster,471,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0
Exodus: Gods and Kings,517,"Action,Adventure,Drama",The defiant leader Moses rises up against the ...,Ridley Scott,"Christian Bale, Joel Edgerton, Ben Kingsley, S...",2014,150,6.0,137299,65.01,52.0

In [ ]:
df_movies_ridley_scott.shape

(8, 11)

In [ ]:
df_movies_ridley_scott_christopher_nolan = df_movies[(df_movies ['director'] == 'Ridley Scott') | (df_movies['director']== 'Christopher Nolan')]
df_movies_ridley_scott_christopher_nolan.head()

,rank,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore
title,,,,,,,,,,,
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
The Prestige,65,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0

In [ ]:
df_movies_multi_filter = df_movies[
    ((df_movies['year'] >= 2005) & (df_movies['year'] <= 2010))
    & (df_movies['rating'] > 8.0)
    & (df_movies['revenue_in_millions'] < df_movies['revenue_in_millions'].quantile(0.25))
]

# Check the contents
df_movies_multi_filter

,rank,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore
title,,,,,,,,,,,
3 Idiots,431,"Comedy,Drama",Two friends are searching for their long lost ...,Rajkumar Hirani,"Aamir Khan, Madhavan, Mona Singh, Sharman Joshi",2009,170,8.4,238789,6.52,67.0
The Lives of Others,477,"Drama,Thriller","In 1984 East Berlin, an agent of the secret po...",Florian Henckel von Donnersmarck,"Ulrich Mühe, Martina Gedeck,Sebastian Koch, Ul...",2006,137,8.5,278103,11.28,89.0
Incendies,714,"Drama,Mystery,War",Twins journey to the Middle East to discover t...,Denis Villeneuve,"Lubna Azabal, Mélissa Désormeaux-Poulin, Maxim...",2010,131,8.2,92863,6.86,80.0
Taare Zameen Par,992,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0

In [ ]:
# iterating over rows in a dataframe
df_small = df_movies[:100]

df_small.shape

(100, 11)

In [ ]:
%%time
for ind in df_small.index:
    print(df_small['director'][ind], df_small['revenue_in_millions'][ind])

James Gunn 333.13
Ridley Scott 126.46
M. Night Shyamalan 138.12
Christophe Lourdelet 270.32
David Ayer 325.02
Yimou Zhang 45.13
Damien Chazelle 151.06
James Gray 8.01
Morten Tyldum 100.01
David Yates 234.02
Theodore Melfi 169.27
Gareth Edwards 532.17
Ron Clements 248.75
Nacho Vigalondo 2.87
Chris Renaud 368.31
Mel Gibson 67.12
Paul Greengrass 162.16
Garth Davis 51.69
Denis Villeneuve 100.5
Stephen Gaghan 7.22
Kenneth Lonergan 47.7
Walt Dohrn 153.69
Roland Emmerich 103.14
Jon Lucas 113.08
Justin Kurzel 54.65
John Hamburg 60.31
Tom Ford 10.64
Bryan Singer 155.33
Tim Miller 363.02
Paul W.S. Anderson 26.84
Anthony Russo 408.08
Christopher Nolan 187.99
Scott Derrickson 232.6
Antoine Fuqua 93.38
Greg Tiernan 97.66
Barry Jenkins 27.85
John Lee Hancock 12.79
Ricardo de Montreuil 4.21
Rob Marshall 241.06
John Madden 3.44
Justin Lin 158.8
J.J. Abrams 936.63
Anna Foerster 30.35
Garry Marshall 32.46
Chad Stahelski 43.0
Christopher Nolan 533.32
Martin Scorsese 7.08
Fede Alvarez 89.21
Thea Sharrock 56.23
Lone Scherfig 3.18
Clint Eastwood 125.07
Zack Snyder 330.25
Tate Taylor 75.31
Sam Taylor-Johnson 166.15
Christopher Nolan 53.08
Matthew Vaughn 128.25
Peter Berg 31.86
George Miller 153.63
Robin Swicord 0.01
Peter Berg 61.28
Robert Zemeckis 40.07
J.A. Bayona 3.73
David Frankel 30.98
Byron Howard 341.26
Gore Verbinski 309.4
Joss Whedon 623.28
Quentin Tarantino 120.52
Gore Verbinski 423.03
Paul Feig 128.34
Christopher Nolan 292.57
Matt Ross 5.88
Martin Scorsese 116.87
David Fincher 167.74
James Wan 350.03
Colin Trevorrow 652.18
Ben Affleck 10.38
James Cameron 760.51
Quentin Tarantino 54.12
Gavin O'Connor 86.2
Denis Villeneuve 60.96
Duncan Jones 47.17
Tate Taylor 169.71
Todd Phillips 43.02
Joss Whedon 458.99
Shane Black 36.25
Makoto Shinkai 4.68
Jeremy Gillespie 0.15
Olivier Assayas 1.29
Martin Scorsese 132.37
Brian Helgeland 1.87
Kenneth Branagh 181.02
Ridley Scott 228.43
Guy Ritchie 45.43
David Mackenzie 26.86
Taylor Hackford 1.66
David Yates 126.59
Alex Garland 25.44
Greg McLean 10.16
Steve McQueen 56.67
Zack Snyder 210.59
CPU times: user 9.2 ms, sys: 35 µs, total: 9.24 ms
Wall time: 11.5 ms

In [ ]:
#iterrows() also can be used for iterating over rows.
%%time
for index, row in df_small.iterrows():
  print(row["director"], row["revenue_in_millions"])

James Gunn 333.13
Ridley Scott 126.46
M. Night Shyamalan 138.12
Christophe Lourdelet 270.32
David Ayer 325.02
Yimou Zhang 45.13
Damien Chazelle 151.06
James Gray 8.01
Morten Tyldum 100.01
David Yates 234.02
Theodore Melfi 169.27
Gareth Edwards 532.17
Ron Clements 248.75
Nacho Vigalondo 2.87
Chris Renaud 368.31
Mel Gibson 67.12
Paul Greengrass 162.16
Garth Davis 51.69
Denis Villeneuve 100.5
Stephen Gaghan 7.22
Kenneth Lonergan 47.7
Walt Dohrn 153.69
Roland Emmerich 103.14
Jon Lucas 113.08
Justin Kurzel 54.65
John Hamburg 60.31
Tom Ford 10.64
Bryan Singer 155.33
Tim Miller 363.02
Paul W.S. Anderson 26.84
Anthony Russo 408.08
Christopher Nolan 187.99
Scott Derrickson 232.6
Antoine Fuqua 93.38
Greg Tiernan 97.66
Barry Jenkins 27.85
John Lee Hancock 12.79
Ricardo de Montreuil 4.21
Rob Marshall 241.06
John Madden 3.44
Justin Lin 158.8
J.J. Abrams 936.63
Anna Foerster 30.35
Garry Marshall 32.46
Chad Stahelski 43.0
Christopher Nolan 533.32
Martin Scorsese 7.08
Fede Alvarez 89.21
Thea Sharrock 56.23
Lone Scherfig 3.18
Clint Eastwood 125.07
Zack Snyder 330.25
Tate Taylor 75.31
Sam Taylor-Johnson 166.15
Christopher Nolan 53.08
Matthew Vaughn 128.25
Peter Berg 31.86
George Miller 153.63
Robin Swicord 0.01
Peter Berg 61.28
Robert Zemeckis 40.07
J.A. Bayona 3.73
David Frankel 30.98
Byron Howard 341.26
Gore Verbinski 309.4
Joss Whedon 623.28
Quentin Tarantino 120.52
Gore Verbinski 423.03
Paul Feig 128.34
Christopher Nolan 292.57
Matt Ross 5.88
Martin Scorsese 116.87
David Fincher 167.74
James Wan 350.03
Colin Trevorrow 652.18
Ben Affleck 10.38
James Cameron 760.51
Quentin Tarantino 54.12
Gavin O'Connor 86.2
Denis Villeneuve 60.96
Duncan Jones 47.17
Tate Taylor 169.71
Todd Phillips 43.02
Joss Whedon 458.99
Shane Black 36.25
Makoto Shinkai 4.68
Jeremy Gillespie 0.15
Olivier Assayas 1.29
Martin Scorsese 132.37
Brian Helgeland 1.87
Kenneth Branagh 181.02
Ridley Scott 228.43
Guy Ritchie 45.43
David Mackenzie 26.86
Taylor Hackford 1.66
David Yates 126.59
Alex Garland 25.44
Greg McLean 10.16
Steve McQueen 56.67
Zack Snyder 210.59
CPU times: user 59.4 ms, sys: 6.11 ms, total: 65.5 ms
Wall time: 63.2 ms

In [ ]:
# itertuples()
%%time
for row in df_small.itertuples():
  print(row.director, row.revenue_in_millions)

James Gunn 333.13
Ridley Scott 126.46
M. Night Shyamalan 138.12
Christophe Lourdelet 270.32
David Ayer 325.02
Yimou Zhang 45.13
Damien Chazelle 151.06
James Gray 8.01
Morten Tyldum 100.01
David Yates 234.02
Theodore Melfi 169.27
Gareth Edwards 532.17
Ron Clements 248.75
Nacho Vigalondo 2.87
Chris Renaud 368.31
Mel Gibson 67.12
Paul Greengrass 162.16
Garth Davis 51.69
Denis Villeneuve 100.5
Stephen Gaghan 7.22
Kenneth Lonergan 47.7
Walt Dohrn 153.69
Roland Emmerich 103.14
Jon Lucas 113.08
Justin Kurzel 54.65
John Hamburg 60.31
Tom Ford 10.64
Bryan Singer 155.33
Tim Miller 363.02
Paul W.S. Anderson 26.84
Anthony Russo 408.08
Christopher Nolan 187.99
Scott Derrickson 232.6
Antoine Fuqua 93.38
Greg Tiernan 97.66
Barry Jenkins 27.85
John Lee Hancock 12.79
Ricardo de Montreuil 4.21
Rob Marshall 241.06
John Madden 3.44
Justin Lin 158.8
J.J. Abrams 936.63
Anna Foerster 30.35
Garry Marshall 32.46
Chad Stahelski 43.0
Christopher Nolan 533.32
Martin Scorsese 7.08
Fede Alvarez 89.21
Thea Sharrock 56.23
Lone Scherfig 3.18
Clint Eastwood 125.07
Zack Snyder 330.25
Tate Taylor 75.31
Sam Taylor-Johnson 166.15
Christopher Nolan 53.08
Matthew Vaughn 128.25
Peter Berg 31.86
George Miller 153.63
Robin Swicord 0.01
Peter Berg 61.28
Robert Zemeckis 40.07
J.A. Bayona 3.73
David Frankel 30.98
Byron Howard 341.26
Gore Verbinski 309.4
Joss Whedon 623.28
Quentin Tarantino 120.52
Gore Verbinski 423.03
Paul Feig 128.34
Christopher Nolan 292.57
Matt Ross 5.88
Martin Scorsese 116.87
David Fincher 167.74
James Wan 350.03
Colin Trevorrow 652.18
Ben Affleck 10.38
James Cameron 760.51
Quentin Tarantino 54.12
Gavin O'Connor 86.2
Denis Villeneuve 60.96
Duncan Jones 47.17
Tate Taylor 169.71
Todd Phillips 43.02
Joss Whedon 458.99
Shane Black 36.25
Makoto Shinkai 4.68
Jeremy Gillespie 0.15
Olivier Assayas 1.29
Martin Scorsese 132.37
Brian Helgeland 1.87
Kenneth Branagh 181.02
Ridley Scott 228.43
Guy Ritchie 45.43
David Mackenzie 26.86
Taylor Hackford 1.66
David Yates 126.59
Alex Garland 25.44
Greg McLean 10.16
Steve McQueen 56.67
Zack Snyder 210.59
CPU times: user 60.6 ms, sys: 5.22 ms, total: 65.8 ms
Wall time: 64.6 ms

In [ ]:
# list to carry all geners
genre_lst = list()
# loop over all rows using itertuples() [the fastest]
for row in df_movies.itertuples():
    # split every genre by the ',' then add this to genre_lst
    genre_lst += row.genre.split(',')

genre_lst[:20]

['Action',
 'Adventure',
 'Sci-Fi',
 'Adventure',
 'Mystery',
 'Sci-Fi',
 'Horror',
 'Thriller',
 'Animation',
 'Comedy',
 'Family',
 'Action',
 'Adventure',
 'Fantasy',
 'Action',
 'Adventure',
 'Fantasy',
 'Comedy',
 'Drama',
 'Music']

In [ ]:
from collections import Counter

Counter(genre_lst).most_common()

[('Drama', 419),
 ('Action', 277),
 ('Comedy', 250),
 ('Adventure', 244),
 ('Thriller', 148),
 ('Crime', 126),
 ('Romance', 120),
 ('Sci-Fi', 107),
 ('Fantasy', 92),
 ('Horror', 87),
 ('Mystery', 86),
 ('Biography', 67),
 ('Family', 48),
 ('Animation', 45),
 ('History', 25),
 ('Music', 15),
 ('Sport', 15),
 ('War', 10),
 ('Musical', 5),
 ('Western', 4)]

In [ ]:
# creating or removing columns from dataframe
#apply() function is used to apply some function agnist some axis
df_movies['rating_category'] = df_movies['rating'].apply(lambda x : 'good' if x >= 8 else 'neutral' )
df_movies.head(10)

,rank,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore,rating_category
title,,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,good
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,neutral
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,neutral
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,neutral
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,neutral
The Great Wall,6,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0,neutral
La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0,good
The Lost City of Z,9,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0,neutral
Passengers,10,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0,neutral
Fantastic Beasts and Where to Find Them,11,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0,neutral

In [ ]:
lng_prof_lst= list()
for row in df_movies.itertuples():
  if row.runtime_in_minutes > 120 and row.revenue_in_millions >100:
    lng_prof_lst.append('long_profitable')
  elif row.runtime_in_minutes <120 and row.revenue_in_millions > 100:
    lng_prof_lst.append('short_profitable')
  elif row.runtime_in_minutes >120 and row.revenue_in_millions < 100:
    lng_prof_lst.append('long_unprofitable')
  else:
    lng_prof_lst.append('short_unfrofitable')

lng_prof_lst[:20]

['long_profitable',
 'long_profitable',
 'short_profitable',
 'short_profitable',
 'long_profitable',
 'short_unfrofitable',
 'long_profitable',
 'long_unprofitable',
 'short_profitable',
 'long_profitable',
 'long_profitable',
 'long_profitable',
 'short_profitable',
 'short_unfrofitable',
 'short_profitable',
 'long_unprofitable',
 'long_profitable',
 'short_unfrofitable',
 'short_profitable',
 'short_unfrofitable']

In [ ]:
df_movies.insert(1,"long_profitable_flg", lng_prof_lst)
df_movies.head()

,rank,long_profitable_flg,genre,description,director,actors,year,runtime_in_minutes,rating,votes,revenue_in_millions,metascore,rating_category
title,,,,,,,,,,,,,
Guardians of the Galaxy,1,long_profitable,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,good
Prometheus,2,long_profitable,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,neutral
Split,3,short_profitable,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,neutral
Sing,4,short_profitable,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,neutral
Suicide Squad,5,long_profitable,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,neutral

In [ ]:
#df[column].value_counts(): this method can count every category in a dataframe. It can has an argument called normalize when its true the result will be in percentage.
df_movies['long_profitable_flg'].value_counts()

long_profitable_flg
short_unfrofitable    454
long_unprofitable     142
short_profitable      123
long_profitable       119
Name: count, dtype: int64

In [ ]:
df_movies["long_profitable_flg"].value_counts(normalize=True)

long_profitable_flg
short_unfrofitable    0.541766
long_unprofitable     0.169451
short_profitable      0.146778
long_profitable       0.142005
Name: proportion, dtype: float64

In [ ]:
df_movies.drop('metascore', axis=1, inplace = True)
df_movies.columns

Index(['rank', 'long_profitable_flg', 'genre', 'description', 'director',
       'actors', 'year', 'runtime_in_minutes', 'rating', 'votes',
       'revenue_in_millions', 'rating_category'],
      dtype='object')

In [ ]:
# data reshaping
# converting from long to wide format :pd.pivot_table(df, index=['column_names'], columns= 'column_name', values = 'column_name, aggfunc)`
# converting from wide to long format : pd.melt(df, id_vars=[column_names], value_vars=[column_names], var_name='name', value_name = 'name')
data = {'Name': ['John', 'Smith', 'Liz',],
        'Weight': [150, 170, 110],
        'BP': [120, 130, 100]}

df_wide = pd.DataFrame(data)

df_wide

    Name  Weight   BP
0   John     150  120
1  Smith     170  130
2    Liz     110  100

In [ ]:
df_long = df_wide.melt(id_vars='Name', var_name='key', value_name='value')

df_long

    Name     key  value
0   John  Weight    150
1  Smith  Weight    170
2    Liz  Weight    110
3   John      BP    120
4  Smith      BP    130
5    Liz      BP    100